language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 5.7
  - hhvm

before_script:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.0.0"
  - composer install --prefer-source --no-interaction
